### ISSUE TITLE
Make habit boxes all the same size? 

### ISSUE THREAD

**Issue by SchoolyB** [DenisGithuku/Intimo#33]
After first launching the app when prompted to choose my habits the UI is a bit off putting due to the fact that the "boxes" contain the habit text and emojis are different sizes presumably because of the extra characters in some of them.

Would it be possible to make all of these boxes the same size evenly across the UI?

Device: Galaxy A53
UI One Version: 6.1
Android Version: 14

Also UI could benifit from moving the "Get Started" button to the bottom of the screen. 

![Screenshot_20240818_225330_Intimo.jpg](https://github.com/user-attachments/assets/1f1e2e5f-7833-4d61-a413-03b119bb6fd5)

**Comment by DenisGithuku** [comment]
Hello Marshall. First of all thank you for taking the time to install the app and give feedback. The habit selection screen uses a staggered grid for the habit cards but now looking at it, it sure could use some UI refresh. I'll work on that by perhaps sticking to one word habit titles.

**Comment by SchoolyB** [comment]
I think that a great Idea

**Comment by DenisGithuku** [comment]
I have worked on it and resolved the changes. Now it's more appealing and coherent.
